### ISSUE TITLE
Watchdog Dev got an error on RPi2

### ISSUE THREAD

**Issue by hallychou** [alex107ivanov/hassio-addons#5]
> 2023-10-30 15:38:55 INFO     Opening watchdog device
> Traceback (most recent call last):
>   File "/watchdog.py", line 42, in <module>
>     app.run()
>   File "/watchdog.py", line 20, in run
>     self.wdt = watchdog('/dev/watchdog')
> OSError: [Errno 16] Resource busy: '/dev/watchdog'

I tried to run the command `echo 1 > /dev/watchdog`, and got a permission error. It seems that the watchdog is in use by the system.

**Comment by ZdenekM** [comment]
The same problem here. Maybe the HA itself started to use the watchdog?

**Comment by chkru** [comment]
Get the following error message:
---
INFO     Opening watchdog device
Traceback (most recent call last):
File "/watchdog.py", line 42, in <module>
app.run()
File "/watchdog.py", line 20, in run
self.wdt = watchdog('/dev/watchdog')
FileNotFoundError: [Errno 2] No such file or directory: '/dev/watchdog'
---
Any idea how to solve?
