### ISSUE TITLE
Failing on RPI4 

### ISSUE THREAD

**Issue by tbowmo** [alex107ivanov/hassio-addons#8]
Fairly new to home-assistant, and wanted to add some watchdog niceness to my rpi4 running haos, however the logs for watchdog-dev are filled with the messages below, indicating that this is not working.

```
024-10-13 18:47:15 INFO     Opening watchdog device
Traceback (most recent call last):
  File "/watchdog.py", line 42, in <module>
    app.run()
  File "/watchdog.py", line 20, in run
    self.wdt = watchdog('/dev/watchdog')
OSError: [Errno 16] Resource busy: '/dev/watchdog'
```

version details
```
  OS Version:               Home Assistant OS 13.1
  Home Assistant Core:      2024.10.2
```

**Comment by MadScientist67** [comment]
I'm having the same issue. Any resolution?

**Comment by KaiBehrends96** [comment]
I have the same issue
